# Generated by Django 4.1 on 2022-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_employee_company_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userProfile',
            field=models.ManyToManyField(blank=True, to='data.userprofile'),
        ),
    ]
