# Generated by Django 4.1 on 2022-08-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.ManyToManyField(related_name='profile', to='accounts.projects'),
        ),
    ]
